version: '3'

services:

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: stasy
    volumes:
      - ./mariadb:/var/lib/mysql

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=stasy
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - API_ADMIN_USERNAME=admin
      - API_ADMIN_PASSWORD=admin
    depends_on:
      - mariadb

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api

