CREATE TABLE Products (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Barcode CHAR(13) UNIQUE NOT NULL,
    Name VARCHAR(150) NOT NULL,
    Manufacturer VARCHAR(150) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Price DECIMAL(7, 2),
    Quantity INT NOT NULL
);