CREATE TABLE Sales (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Date DATETIME NOT NULL,
    CustomerName VARCHAR(255) NOT NULL,
    SellerID VARCHAR(36) NOT NULL,
    Total DECIMAL(7, 2) NOT NULL,
    FOREIGN KEY (SellerID) REFERENCES Users(ID)
);
